query Blogs($slug: String!) {
  blogs(filters: { slug: { eq: $slug } }) {
    data {
      id
      attributes {
        title
        subtitle
        slug
        metaTitle
        metaDescription
        content
        image {
          data {
            attributes {
              url
            }
          }
        }
        category {
          data {
            id
            attributes {
              name
              slug
            }
          }
        }
        publishedAt
      }
    }
  }
}
