    query Categories($slug: String!){
      categories(filters: { slug: { eq: $slug } }) {
        data {
          id
          attributes {
            slug
            name
            metaTitle
            metaDescription
            blogs {
              data {
                id
                attributes {
                  title
                  subtitle
                  content
                  image {
                    data {
                      attributes {
                        url
                      }
                    }
                  }
                  category {
                    data {
                      id
                      attributes {
                        slug
                        name
                        metaTitle
                        metaDescription
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
